{{- $name := include "labbox.api.docker" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $name }}
  labels:
    {{- include "labbox.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "labbox.selectorLabels" . | nindent 6 }}
      name: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "labbox.selectorLabels" . | nindent 8 }}
        name: {{ $name }}
    spec:
    {{- with .Values.docker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.docker.image.repository }}:{{ .Values.docker.image.tag }}"
          imagePullPolicy: {{ .Values.docker.image.pullPolicy }}
          ports:
          - containerPort: 3476
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3476
          readinessProbe:
            httpGet:
              path: /
              port: 3476
          volumeMounts:
          {{- if and .Values.docker.subpath .Values.docker.persistentVolumeClaim }}
          - name: volume
            mountPath: /app
            subPath: {{ .Values.docker.subpath }}
          {{- end }}
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath: 
          path: /var/run/docker.sock
      {{- with .Values.docker.persistentVolumeClaim }}
      - name: volume
        persistentVolumeClaim:
          claimName: {{ . }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
