{{- $name := include "labbox.main" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "labbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.main.replicaCount }}
  selector:
    matchLabels:
      {{- include "labbox.selectorLabels" . | nindent 6 }}
      name: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "labbox.selectorLabels" . | nindent 8 }}
        name: {{ $name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.main.image.repository }}:{{ .Values.main.image.tag }}"
          imagePullPolicy: {{ .Values.main.image.pullPolicy }}
          ports:
          - containerPort: 5000
            protocol: TCP
          env:
          - name: FLASK_APP
            value: labboxmain
          - name: NAME_K8SAPI
            value: {{ include "labbox.api.k8s" . }}
          - name: NAME_REDIS
            value: {{ include "labbox.main.redis" . }}
          volumeMounts:
          {{- if .Values.main.persistentVolumeClaim }}
          {{- with .Values.main.subpath }}
          - name: volume
            mountPath: /app
            subPath: {{ . }}
            readOnly: true
          {{- end }}
          {{- with .Values.main.data_subpath }}
          - name: volume
            mountPath: /data
            subPath: {{ . }}
          {{- end }}
          {{- end }}
      dnsPolicy: ClusterFirst
      volumes:
      {{- with .Values.main.persistentVolumeClaim }}
      - name: volume
        persistentVolumeClaim:
          claimName: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
