{{- if .Values.email_sender.enabled -}}
{{- $name := include "labbox.email_sender" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "labbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.email_sender.replicaCount }}
  selector:
    matchLabels:
      {{- include "labbox.selectorLabels" . | nindent 6 }}
      name: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "labbox.selectorLabels" . | nindent 8 }}
        name: {{ $name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.email_sender.image.repository }}:{{ .Values.email_sender.image.tag }}"
          imagePullPolicy: {{ .Values.email_sender.image.pullPolicy }}
          env:
          - name: EMAIL_HOST
            value: {{ .Values.email_sender.host }}
          - name: EMAIL_PORT
            value: "{{ .Values.email_sender.port }}"
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.email_sender.secret_name }}
                key: user
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.email_sender.secret_name }}
                key: password
          ports:
            - containerPort: 5870
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5870
          readinessProbe:
            httpGet:
              path: /
              port: 5870
          volumeMounts:
          {{- if .Values.email_sender.persistentVolumeClaim }}
          {{- with .Values.email_sender.subpath }}
          - name: volume
            mountPath: /app
            subPath: {{ . }}
            readOnly: true
          {{- end }}
          {{- end }}
      dnsPolicy: ClusterFirst
      volumes:
      {{- with .Values.email_sender.persistentVolumeClaim }}
      - name: volume
        persistentVolumeClaim:
          claimName: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
