{{- if .Values.vnc.enabled -}}
{{- $name := include "labbox.policy" . -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}
  namespace: {{ .Values.k8s.namespace }}
  labels:
    {{- include "labbox.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{ .Values.k8s.user_label }}: "true"
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except: 
        - 10.90.0.0/16
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}
