{{- $name := include "labbox.api.k8s" . -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}
  labels:
    {{- include "labbox.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "create", "delete"]

- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete"]

- apiGroups: [""]
  resources: ["pods/exec", "pods/log"]
  verbs: ["create", "get", "list"]

- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $name }}
  labels:
    {{- include "labbox.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ $name }}
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "labbox.labels" . | nindent 4 }}
---
