---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - http:
      paths:
      - path: /jupyter/{{ name }}
        backend:
          serviceName: {{ name }}
          servicePort: 8000
