apiVersion: v1
kind: Pod
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    {{ label }}: "true"
    labbox-pod-name: {{ name }}
spec:
  restartPolicy: Never
  {% if node %}
  nodeSelector:
    kubernetes.io/hostname: {{ node }}
  {% endif %}

  initContainers:
  - name: add-files-to-home
    image: busybox
    command: ["sh", "-c", "chown 1000:1000 /home/ubuntu && chmod 700 /home/ubuntu && tar xf /all.tar -C /home/ubuntu"]
    volumeMounts:
    - name: homenas
      mountPath: /all.tar
      subPath: {{ inittar | default("all.tar") }}
      readOnly: true
    - name: homenas
      mountPath: /home/ubuntu
      subPath: {{ homepath }}

  containers:
  - name: main
    image: {{ image }}
    imagePullPolicy: {{ "Always" if pull.lower() == 'true' else 'IfNotPresent' }}

    {% if command %}
    command: [sudo]
    args: ["bash", "-c"]
    {% endif %}

    {% if not command %}
    ports:
    - containerPort: 22
    - containerPort: 5900
    - containerPort: 8000
    {% endif %}

    volumeMounts:
    {% if naspvc %}
    - name: labnas
      mountPath: /home/nas
    {% endif %}
    - name: homenas
      mountPath: /home/ubuntu
      subPath: {{ homepath }}
    - name: homenas
      mountPath: /home/share
      subPath: share
    - name: dshm
      mountPath: /dev/shm
    - name: tmp
      mountPath: /home/tmp

    env:
    - name: node
      value: {{ node | default("any") }}
    {% if gpu is not none %}
    - name: NVIDIA_VISIBLE_DEVICES
      value: "{{ gpu }}"
    {% endif %}

    resources:
      requests:
        memory: "1Mi"
      limits:
        memory: "20Gi"

  volumes:
  {% if naspvc %}
  - name: labnas
    persistentVolumeClaim:
      claimName: {{ naspvc }}
  {% endif %}
  - name: homenas
    persistentVolumeClaim:
      claimName: {{ homepvc }}
  - name: dshm
    emptyDir:
      medium: Memory
  - name: tmp
    emptyDir: {}
